services:
  tts-app:
    container_name: tts-backend
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    ports:
      - "8989:8989"
    volumes:
      - ./backend/src:/app
      - ./audio_output:/audio_output
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - LOCAL_DEVELOPMENT=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  streamlit-app:
    container_name: tts-frontend
    build:
      context: /streamlit_app
    ports:
      - "5555:8501"
    volumes:
      - ./streamlit_app/src:/app
    environment:
      - PYTHONUNBUFFERED=1
